export const ACTION_TYPES = {
    ADD_NEW_SCHOOL: "ADD_NEW_SCHOOL",
    UPDATE_DATA_SCHOOL: "UPDATE_DATA_SCHOOL",
    REGISTER_COURSE: "REGISTER_COURSE",
    START_NEW_GROUP: "START_NEW_GROUP",
    PASSING_LESSON: "PASSING_LESSON",
    END_GROUP: "END_GROUP",
    UPDATE_SELECTED_SCHOOL: "UPDATE_SELECTED_SCHOOL",
    UPDATE_SELECTED_COURSE: "UPDATE_SELECTED_COURSE"
}